# Netlify Configuration
[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'No build command needed for static site'"

[build.environment]
  NODE_VERSION = "18"
  ACTIVE_PROVIDER = "NETLIFY"
  GTM_ID = "GTM-WKL8V4L"

# Redirects for API functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirects for admin functions
[[redirects]]
  from = "/admin/api/*"
  to = "/.netlify/functions/netlify-admin/:splat"
  status = 200

# Redirects for lead management
[[redirects]]
  from = "/api/leads/*"
  to = "/.netlify/functions/netlify-leads/:splat"
  status = 200

# Redirects for image management
[[redirects]]
  from = "/api/images/*"
  to = "/.netlify/functions/netlify-images/:splat"
  status = 200

# Redirects for analytics
[[redirects]]
  from = "/api/analytics/*"
  to = "/.netlify/functions/netlify-analytics/:splat"
  status = 200

# CMS redirects
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for admin pages
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Headers for API functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization" 